service: iagro-beifong

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 2048
  timeout: 15
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  extract_new_records:
    handler: src/scripts/extract_new_records.handler
    events:
    #  - schedule: cron(0/5 * * * ? *)
      - schedule: cron(59 23 * * ? *)
