version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.16.1-stretch

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: iagro-test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    environment:
      NODE_ENV: test
      DB_NAME: iagro-test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DUMMY_TOKEN: eyJraWQiOiJMT0V5Tk5nUWxJV1l1Y2pjV0ZFV2ZndzBpRE13MHFsaFwvOHJrODM4K2I3cz0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiREd6NHE5cVdXWE9wS25tbm14WDk0ZyIsInN1YiI6IjUyYzNlMDQ3LTdlN2MtNDc0YS1hYmZjLTAwMjhiYzJiZjM5MSIsImF1ZCI6IjM4N3BnOHJtcWs4NWplYmlkN3QwYzNlMmtqIiwiZXZlbnRfaWQiOiIzM2Q3ZDNlOC1iZjM0LTRjYTgtYWIwNi01MDMyMjZhNDUyYzkiLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTYxNTk4NDQwMSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfbWhoMlVJRkdzIiwiY29nbml0bzp1c2VybmFtZSI6ImNhbWlsbyIsImV4cCI6MTYxNTk4ODAwMSwiaWF0IjoxNjE1OTg0NDAxfQ.tEsCAYyxgeOzyP1UXeRtuzEFxNXqaZcxyOgSTkf6zfdo2uKwwZLEUw6ni5BWANhBEHoQ3hk7AgExVF3DEFxee_Ys_U2UKBy1qkuv4RQuxFRjFCCEtmMrwu9M-iGI1GeYKSgJl6pN5fOzGo-OB-nYbNWGhlw_DIFcX-GmEaVK2kb7sxpGLdL9DJ4N_wWoywyhD4B7vulonhDBJUQdnyOf3wMf3Ow_19HxRQpxWHWOQfmVw8dmHtUMxTWJOWYJ_OKxwWOrPX6otqPEwmRoG4svtFbXh0rLQNEqEx4k4xD6HkqW-cYEp03yWf7Rah1Rf_khvZi5iHyeuHwgaw-GiAly4w


    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run database migrations
          command: npm run knex

      - run:
          name: Applying binary permissions
          command: chmod u+x bin/startServices.sh bin/stopServices.sh

      - run:
          name: Run linter checks
          command: npm run lint:js

      - run:
          name: Run tests
          command: npm run test
